uploads = []
generated = []

[[outputs]]
id = "ccSGxi_Me66ERD5i04dLE"
uri = "file://scripts/assets/richmenu.png"
type = "image"
title = "LINE 圖文選單"

[[outputs]]
id = "IzlONwfHkPlmV6IqGUKFS"
uri = "file://attached_assets/screenshots/b6f4ddb7-622f-4141-98d4-8e2f60059ab9-00-10x8gz8oemofu_kirk_replit_dev_mockup_preview_line-cards_TabbedMenu.png"
type = "image"
title = "頁籤式主選單設計稿"
