// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/line-cards/Bento.tsx": () => import("../components/mockups/line-cards/Bento.tsx"),
  "./components/mockups/line-cards/Hero.tsx": () => import("../components/mockups/line-cards/Hero.tsx"),
  "./components/mockups/line-cards/PremiumDark.tsx": () => import("../components/mockups/line-cards/PremiumDark.tsx"),
  "./components/mockups/line-cards/Refined.tsx": () => import("../components/mockups/line-cards/Refined.tsx"),
  "./components/mockups/line-cards/Segmented.tsx": () => import("../components/mockups/line-cards/Segmented.tsx"),
  "./components/mockups/line-cards/TabbedMenu.tsx": () => import("../components/mockups/line-cards/TabbedMenu.tsx")
};
